name: Test Backend

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install Dependencies
        working-directory: ./backend
        run: npm install
        
      - name: Run Build Check
        working-directory: ./backend
        run: npm run build
        
      - name: Start Backend Server
        working-directory: ./backend
        run: |
          npm start &
          sleep 30
          kill %1
        env:
          CI: true
